import { Inter } from "next/font/google";
import "./globals.css";

import { ThemeProvider } from "../components/theme-provider";

import BottomNav from "../components/BottomNav";

const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className + " bg-orange-100"}>
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          {children}
          <BottomNav />
        </ThemeProvider>
      </body>
    </html>
  );
}
